### ISSUE TITLE
Crash on 1.17.1 Server

### ISSUE THREAD

**Issue by Herczog** [jexline/exline-furniture#2]
Hi, I saw in comments that you started an issue page. Here is the crash log from my 1.17.1 server running Forge 37.0.30 (hosted on Apex). We do have numerous other mods loaded so not sure if it could be an incompatibility.

Thanks for your time!

-----------------------

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/8/21, 12:18 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fmllegacy.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.17.1-37.0.30-universal.jar%2337!:?] {re:classloading}
	at net.minecraftforge.fmllegacy.server.ServerModLoader.load(ServerModLoader.java:52) ~[forge-1.17.1-37.0.30-universal.jar%2337!:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:100) ~[server-1.17.1-20210706.113038-srg.jar%2333!:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.30.jar%2321!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.46.jar:?] {}
-- MOD exlinefurniture --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderType
		at com.exline.exlinefurniture.RenderCutouts.<init>(RenderCutouts.java:8) ~[exlinefurniture-1.17.1.jar%2326!:1.17.1] {re:classloading}
		at com.exline.exlinefurniture.ExlineFurnitureMain.setup(ExlineFurnitureMain.java:28) ~[exlinefurniture-1.17.1.jar%2326!:1.17.1] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.30.jar%2335!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.30.jar%2334!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: exlinefurniture-1.17.1.jar
	Failure message: Exline's Furniture Mod (exlinefurniture) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderType
	Mod Version: 1.17.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderType
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at com.exline.exlinefurniture.RenderCutouts.<init>(RenderCutouts.java:8) ~[exlinefurniture-1.17.1.jar%2326!:1.17.1] {re:classloading}
	at com.exline.exlinefurniture.ExlineFurnitureMain.setup(ExlineFurnitureMain.java:28) ~[exlinefurniture-1.17.1.jar%2326!:1.17.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.30.jar%2335!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.30.jar%2334!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 3.10.0-1160.36.2.el7.x86_64
	Java Version: 16.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 633216512 bytes (603 MiB) / 1010827264 bytes (964 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 40236.90
	Virtual memory used (MB): 55392.60
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 3877.25
	JVM Flags: 2 total; -Xmx1024M -Xms665M
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |SIDED_SETU|Manifest: NOSIGNATURE
		movingelevators-1.2.34a-mc1.17.jar                |Moving Elevators              |movingelevators               |1.2.34a             |SIDED_SETU|Manifest: NOSIGNATURE
		morevillagers-FORGE-1.17.1-2.1.0.jar              |More Villagers                |morevillagers                 |2.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.17.1-37.0.30-universal.jar                |Forge                         |forge                         |37.0.30             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BiomesOPlenty-1.17.1-14.0.0.32-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.32    |SIDED_SETU|Manifest: NOSIGNATURE
		Xaeros_Minimap_21.14.1_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |21.14.1             |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-doors-1.0.3-mc1.17.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		exlinefurniture-1.17.1.jar                        |Exline's Furniture Mod        |exlinefurniture               |1.17.1              |ERROR     |Manifest: NOSIGNATURE
		cfm-7.0.0pre24-1.17.1.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre24         |SIDED_SETU|Manifest: NOSIGNATURE
		comforts-forge-1.17.1-5.0.0.0.jar                 |Comforts                      |comforts                      |1.17.1-5.0.0.0      |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: cefb0d83-2678-4f64-ba67-255777c9cb91
	FML: 37.0
	Forge: net.minecraftforge:37.0.30

**Comment by jexline** [comment]
Looks like for some reason "net/minecraft/client/renderer/RenderType" is not found. I'm not sure why, I think the version of Forge you are using should have this, but that might be the problem. There is a new Forge update for 1.17.1 right now, it is 37.0.58. I will post an updated mod with that version attached to it. Try updating your forge server if you can and I will upload the new file as soon as possible and link back here as well.

EDIT: Here is the latest version, I would try it out with the latest version of forge. Right now it is 37.0.58, as of writing this. If this still does not work let me know. My internet is not able to run servers, so I haven't tested other than single-player.

EDIT EDIT: That file did not fix the problem so I removed the link. The new version only calls RenderType in the client, so it should work, but I haven't tested yet. I'm still trying to set up my own forge server but I'm having trouble. :)

**Comment by ProsperCraft** [comment]
.58 still crashes when trying to load on a dedicated server.

**Comment by jexline** [comment]
Ok, I think I found the problem. You cannot call RenderType server-side, so I had to change it to be called in client only.
I had to change this;
```
private void setup(final FMLCommonSetupEvent event) {
        new RenderCutouts();
    }
```

to this;
```
private void setup(final FMLClientSetupEvent event) {
        new RenderCutouts();
    }
```

The new file will be linked here once approved.

**Comment by jexline** [comment]
Here is the new file, please let me know if it works.
EDIT: I have been able to get a server up and was able to test it myself. I was able to start the server up and play on it with no problems.

[https://www.curseforge.com/minecraft/mc-mods/exlines-furniture/files/3456936](https://www.curseforge.com/minecraft/mc-mods/exlines-furniture/files/3456936)

**Comment by ProsperCraft** [comment]
This has been resolved, please close the issue.

**Comment by Herczog** [comment]
Works great, thanks for the fix! I threw a couple bucks at your donation link.
