### ISSUE TITLE
Remove unused loot tables

### ISSUE THREAD

**Issue by itsdinkd** [jexline/exline-furniture#6]
you have tons of unused loot tables that are attempted to being loaded in 1.18.1 forge.

this causes spam in the logs 

```java
[09:00:41] [Server thread/ERROR]: Couldn't parse loot table exlinefurniture:blocks/oak_dog_house
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'exlinefurniture:oak_dog_house'
	at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:130) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:130) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:456) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:190) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:187) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:255) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:789) ~[forge-1.18.1-39.0.9-universal.jar%23348!:?]
	at net.minecraft.world.level.storage.loot.LootTables.lambda$apply$0(LootTables.java:41) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at dev.latvian.mods.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:38) ~[kubejs-forge-1801.4.0-build.263.jar%23215!:1801.4.0-build.263]
	at net.minecraft.world.level.storage.loot.LootTables.redirect$zjd000$applyKJS(LootTables.java:521) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:39) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:17) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_129861_(MinecraftServer.java:1287) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.commands.ReloadCommand.m_138235_(ReloadCommand.java:22) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.commands.ReloadCommand.m_138228_(ReloadCommand.java:53) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%2336!:?]
	at net.minecraft.commands.Commands.m_82117_(Commands.java:230) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1134) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1113) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1099) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:30) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:7) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

```java
[09:00:44] [Server thread/ERROR]: Couldn't parse loot table exlinefurniture:blocks/oak_bird_house
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'exlinefurniture:oak_bird_house'
	at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:130) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:130) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:456) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:190) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:187) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:255) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar%2322!:?]
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar%2322!:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:789) ~[forge-1.18.1-39.0.9-universal.jar%23348!:?]
	at net.minecraft.world.level.storage.loot.LootTables.lambda$apply$0(LootTables.java:41) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at dev.latvian.mods.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:38) ~[kubejs-forge-1801.4.0-build.263.jar%23215!:1801.4.0-build.263]
	at net.minecraft.world.level.storage.loot.LootTables.redirect$zjd000$applyKJS(LootTables.java:521) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:39) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:17) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_129861_(MinecraftServer.java:1287) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.commands.ReloadCommand.m_138235_(ReloadCommand.java:22) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.commands.ReloadCommand.m_138228_(ReloadCommand.java:53) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%2336!:?]
	at net.minecraft.commands.Commands.m_82117_(Commands.java:230) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1134) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1113) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1099) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:30) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:7) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23344!:?]
```

**Comment by jexline** [comment]
I have removed the loot tables in the latest version v2.0.2. Thanks for reporting the issue!
EDIT: This is a Fabric fix, Forge Fix coming soon!
